apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-rabbitmqcluster
spec:
  replicas: 3
  resources:
    requests:
      cpu: 250m
      memory: 512Mi 
    limits:
      cpu: 500m
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      log.console.level = info
      channel_max = 700
      default_user= guest 
      default_pass = guest
      default_user_tags.administrator = true
  service:
    type: LoadBalancer
