apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: zivlederer/producer-test
        ports:
        - containerPort: 5000
        env:
        - name: RABBITMQ_HOST
          value: "production-rabbitmqcluster"
---
apiVersion: v1
kind: Service
metadata:
  name: producer-service
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30080  # NodePort should be between 30000-32767

