apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: zivlederer/consumer-test
        env:
        - name: RABBITMQ_HOST
          value: "production-rabbitmqcluster"
